spring:
  datasource:
    username: root
    password: yiqiandewo1
<<<<<<< HEAD
    url: jdbc:mysql://120.24.218.221:3306/second_hand_car?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
=======
    url: jdbc:mysql://119.45.192.221:3306/second_hand_car?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
>>>>>>> d8b129633f409d0020248047f47a130f463bc1d6
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.scsms.pojo
  mapper-locations: classpath:com/scsms/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.scsms.mapper: debug